### ISSUE TITLE
Days in date not generated

### ISSUE THREAD

**Issue by IAM-marco** [TheNomet/FLC#1]
If I set up the `From Date` to
2011/07/03
And the `To Date` to
2011/12/23

With separator `/`, format `DD/MM/YY` and Even/Odd to `normal` the regexp for the days is wrong, this is the generated output:

```
    day30=0
    day31=0
    day_month={day30}"/"(9|11)|{day31}"/"(8|10)|(0)"/"7|(0)"/"12
    year=2011
    date={day_month}"/"{year}
```

**Comment by TheNomet** [comment]
Did you try to import in eclipse the project as a zip file and launching the program from eclipse?
The problem could be that in the executable .jar is not present the folder regexp (in which there is the program for the regular expression). I'll try to fix this, in the meantime try to launch from eclipse and let me know if something goes wrong!
Thanks

**Comment by TheNomet** [comment]
Just remember to change the permissions with chmod

**Comment by IAM-marco** [comment]
Permissions were correct.
Import to Eclipse generates even more errors (cannot import zip file and if I try to import the folder the classpath is probably wrong and Eclipse cannot find the main java file)

**Comment by TheNomet** [comment]
You have to import a new project as a zip file, not just a zip file. Hope you can see the screen shots of my screen.

![first](https://cloud.githubusercontent.com/assets/15369570/18418365/21143932-7845-11e6-9a94-d2e18612b20e.PNG)
![second](https://cloud.githubusercontent.com/assets/15369570/18418367/21209fa6-7845-11e6-8944-52d196c4d9b8.PNG)
![third](https://cloud.githubusercontent.com/assets/15369570/18418368/212a465a-7845-11e6-8cda-81be7ba5b7ce.PNG)
![fourth](https://cloud.githubusercontent.com/assets/15369570/18418366/2116baa4-7845-11e6-940d-b347df3f656c.PNG)

As you can see it's working fine with me: can you provide some image if the problem is still there?

For the executable jar:
- cd _path for DateRegexp directory (or the directory where you have copied DateRegexp.jar and the regexp directory)_
- chmod 777 regexp/*
- java -jar DateRegexp.jar

![last](https://cloud.githubusercontent.com/assets/15369570/18418515/5024aab0-7848-11e6-993d-d3e4acd1a0a8.PNG)

Try this and let me know. I tryed on 2 computers and worked, I hope it will work also on yours!

**Comment by IAM-marco** [comment]
I think I'm missing JavaFX library as the Main file returns import error on `javafx.application.Application`

**Comment by TheNomet** [comment]
It happens when you import the project in eclipse or when you launch from cmd line the .jar? Please try both and let me know. Thanks

**Comment by IAM-marco** [comment]
The program works from the Jar file (double click on it).
The import error is on the source code file Main.java .
However I noticed that if I run the JAR file through command line with `java -jar DateRegexp.jar` it fails and I get:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: application/Main : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by TheNomet** [comment]
That is probably related to the fact that I used java 1.8 to compile, and you have a different version installed on your machine. 
By the way if it is working with the double click is even easier than with the cmd line.
What version of java do you have on your pc?

**Comment by IAM-marco** [comment]
1.7.0_71

**Comment by TheNomet** [comment]
Fixed. Try now, the brach is the one called NoGUI.
